<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>svc</string>
		<string>msg</string>
	</array>
	<key>name</key>
	<string>Service Lang (Svclang)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Message types</string>
			<key>match</key>
			<string>(abstract|query|event|command|partial message|document|responds with|extends|emits)\s(\w+)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Api pieces</string>
			<key>match</key>
			<string>(stream|http)\s(\w+)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Category</string>
			<key>match</key>
			<string>\#\#.*$</string>
			<key>name</key>
			<string>entity.name.section</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A comment</string>
			<key>match</key>
			<string>//.*[\n]?$</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>A multiline comment</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>--</string>
			<key>comment</key>
			<string>A multiline description</string>
			<key>end</key>
			<string>--</string>
			<key>name</key>
			<string>string.unquoted</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>An inline description</string>
			<key>match</key>
			<string>\#.*$</string>
			<key>name</key>
			<string>string.unquoted</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Setting</string>
			<key>match</key>
			<string>^(namespace|service|version)\s+(.+)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Alias</string>
			<key>match</key>
			<string>\s*(\w+)\s*\-\&gt;\s*(\w+)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>Message body</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Section Header</string>
					<key>match</key>
					<string>^\s*(\w|\s)+\s*\:\s*$</string>
					<key>name</key>
					<string>support.constant</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(\w+)</string>
					<key>comment</key>
					<string>Field declaration</string>
					<key>end</key>
					<string>(?=(\#|$))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(string|number|integer|boolean|date|map|list|enum)\s*</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.language</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>primitive type with default</string>
							<key>end</key>
							<string>(\)|(?=\#)|$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>comment</key>
									<string>Default value</string>
									<key>match</key>
									<string>(\w|\.)+</string>
									<key>name</key>
									<string>support.constant</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)\s*\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Type with default</string>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>comment</key>
									<string>Default value</string>
									<key>match</key>
									<string>(\w|\.)+</string>
									<key>name</key>
									<string>support.constant</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>comment</key>
							<string>Type</string>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.svclang</string>
	<key>uuid</key>
	<string>df22d78e-b6a0-4484-8366-e818f287e490</string>
</dict>
</plist>
